[package]
name = "noak"
version = "0.3.0"
authors = ["frozolotl <frozolotl@protonmail.com>"]
edition = "2018"
description = "A library for reading and writing java bytecode fast"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/noak"
repository = "https://gitlab.com/frozo/noak"
categories = ["parser-implementations", "encoding"]
keywords = ["java", "jvm", "class", "bytecode"]

[dependencies]
bitflags = "1.1.0"
num-traits = "0.2.8"
indexmap = "1.1.0"
