[package]
name = "noak"
version = "0.1.0"
authors = ["frozolotl <frozolotl@protonmail.com>"]
edition = "2018"
description = "A library for reading and writing java bytecode as fast and easy as possible"
license = "MIT"
documentation = "https://docs.rs/noak"
repository = "https://gitlab.com/frozo/noak"
homepage = "https://gitlab.com/frozo/noak"

[dependencies]
bitflags = "1.0"
